version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9000:9000
    depends_on:
      - db
  db:
    image: mongo
    environment:
      MONGO_URI_PROD: mongodb://db:27017/mydatabase
      MONGO_URI_DEV: mongodb://db:27017/mydatabase
    ports:
      - 27017:27017
