services:
  - type: web
    name: gesi-backend
    runtime: node
    plan: free
    autoDeploy: false
    buildCommand: npm install -g @nestjs/cli --force && npm install --force
    startCommand: npm run sd
